"""add dep_content

Revision ID: b1c68b02d576
Revises: f5183a1260b5
Create Date: 2023-11-21 01:45:00.056070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c68b02d576'
down_revision = 'f5183a1260b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit_contnet', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_model', schema=None) as batch_op:
        batch_op.drop_column('deposit_contnet')

    # ### end Alembic commands ###
