"""add subject

Revision ID: b602c6f176f4
Revises: 9604b1ea4b0e
Create Date: 2023-11-22 01:50:18.896670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b602c6f176f4'
down_revision = '9604b1ea4b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_model', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
