"""delete tans model

Revision ID: f5183a1260b5
Revises: 1db2258efcb1
Create Date: 2023-11-21 01:09:30.130390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5183a1260b5'
down_revision = '1db2258efcb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.INTEGER(), nullable=True),
    sa.Column('deposit', sa.INTEGER(), nullable=True),
    sa.Column('date_added', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
